### PR TITLE
[GH-71] - preventing traversing class and struct declaration when decting reentrant calls

### LINKED ISSUE #71: Incorrect NS4000 when using typeof expression
I think the analyzer is incorrectly firing `NS4000: Returns() is set with a method that itself calls Returns` for the following code (this is the simplest I could get the code to reproduce the warning I was getting):

```C#
public interface IExample
{
    object Method();
}

public class ExampleTest
{
    [Fact]
    public void TypeofTestClass()
    {
        IExample example = Substitute.For<IExample>();
        example.Method().Returns(typeof(ExampleTest));
        //                       ^^^^^^^^^^^^^^^^^^^
    }
}
```

This is under dotnet-core 2.1 with using NSubstitute version 4.0.0, NSubstitute.Analyzers.CSharp version 1.0.5 and xunit version 2.4.1

Granted, the above code doesn't look realistic (there's no asserts!), however, I was getting the warning in one of my actual tests and it seems to be the `typeof(TheClassContainingTheTest)` that triggers it.

Let me know if there's anything I can do to help.

### PR DESCRIPTION
**Pull request by tpodolak**
Closes #71

### CODE REVIEW

File: src/NSubstitute.Analyzers.VisualBasic/DiagnosticAnalyzers/ReEntrantCallFinder.cs [hunk 1]
```diff
@@ -46,6 +46,14 @@ public override void VisitInvocationExpression(InvocationExpressionSyntax node)
                 base.VisitInvocationExpression(node);
             }
 
+            public override void VisitClassBlock(ClassBlockSyntax node)
+            {
```
Comment (tpodolak) [inline src/NSubstitute.Analyzers.VisualBasic/DiagnosticAnalyzers/ReEntrantCallFinder.cs]: @dtchepak The bug doesn't occur for VB analyzers - at least for the sample code reported in the ticket. However I decided to add this one and one below as a precaution. This will probably drop test coverage by a fraction of percentage.
